# Generated by Django 6.0.4 on 2026-04-15 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('n_clienti_totale', models.IntegerField()),
                ('km_itinerario', models.FloatField()),
                ('destinatario', models.CharField(max_length=255)),
                ('indirizzo_impianto', models.CharField(max_length=255)),
                ('op_min', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer', models.CharField(max_length=20, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('pericoloso', models.BooleanField(default=False)),
                ('t_verg', models.FloatField(blank=True, null=True)),
                ('t_smalt', models.FloatField()),
                ('t_tratt', models.FloatField()),
                ('t_ric', models.FloatField()),
                ('resa', models.FloatField(blank=True, null=True)),
                ('f_equiv', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=20, unique=True)),
                ('modello', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=20)),
                ('euro_class', models.CharField(blank=True, max_length=20, null=True)),
                ('massa_vuoto_kg', models.FloatField()),
                ('portata_kg', models.FloatField()),
                ('co2_km_vuoto_kg', models.FloatField()),
                ('co2_km_pieno_kg', models.FloatField()),
                ('co2_min_kg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_cliente_fisso', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitaLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unita_locali', to='core.azienda')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_formulario', models.CharField(max_length=50)),
                ('ora_ritiro', models.TimeField()),
                ('quantita_kg', models.FloatField()),
                ('d_baricentro_km', models.FloatField()),
                ('pericoloso', models.BooleanField()),
                ('s1_gha', models.FloatField(blank=True, null=True)),
                ('s2_gha', models.FloatField(blank=True, null=True)),
                ('s_gha', models.FloatField(blank=True, null=True)),
                ('gha_terreno', models.FloatField(blank=True, null=True)),
                ('gha_netto', models.FloatField(blank=True, null=True)),
                ('t1_co2', models.FloatField()),
                ('t2_co2', models.FloatField()),
                ('co2_trasporto', models.FloatField()),
                ('giro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentazioni', to='core.giro')),
                ('materiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.materiale')),
                ('unita_locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unitalocale')),
            ],
        ),
        migrations.AddField(
            model_name='giro',
            name='veicolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veicolo'),
        ),
    ]
