# Generated by Django 6.0.4 on 2026-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_materiale_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentazione',
            name='s_gha_tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
